### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by nandosangenetto** [Vivan/HueDefaulter#1]
Hey, how do I make it work?

There's any installation instructions?

**Comment by Vivan** [comment]
What are you hoping to do with it? Currently it only changes the lights to a colour temperature that I personally like, but you can do a lot more with it. It isn't well packaged so any customisation you might want will need to be done in-code but I'm happy to help.

**Comment by nandosangenetto** [comment]
Oh, cool. 

So I just need to change the color and ip variables, and run the python script?

**Comment by Vivan** [comment]
Yes, change the hue to one you like, change the IP to that of your bridge (and, before running the script for the first time, press the button on your bridge). 

There are four different models of the script, you uncomment the one you want. I personally recommend version 2, using a delay of 30 seconds. It puts the least load on your bulbs.
